language: node_js
sudo: false
node_js:
- '0.12'
before_install:
- '/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
cache:
  directories:
  - node_modules
services:
  - mongodb
